# Generated by Django 4.0.2 on 2022-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addstudent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
